[project]
name = "chatapp"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==2.1.0",
    "apscheduler>=3.11.0",
    "dashscope>=1.22.2",
    "fastapi>=0.115.13",
    "flask>=3.1.1",
    "langchain-community>=0.3.25",
    "llama-index>=0.12.42",
    "llama-index-core>=0.12.42",
    "llama-index-embeddings-dashscope>=0.3.0",
    "llama-index-embeddings-langchain>=0.3.0",
    "llama-index-embeddings-openai>=0.3.1",
    "llama-index-llms-dashscope>=0.4.0",
    "llama-index-llms-openai>=0.4.7",
    "llama-index-multi-modal-llms-dashscope>=0.3.0",
    "llama-index-postprocessor-dashscope-rerank>=0.3.0",
    "llama-index-readers-dashscope>=0.3.0",
    "llama-index-readers-file>=0.4.9",
    "llama-index-vector-stores-milvus>=0.8.4",
    "pandas>=2.2.3",
    "pillow>=11.2.1",
    "pydub>=0.25.1",
    "pymilvus>=2.5.11",
    "pytest>=8.4.1",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "requests-toolbelt>=1.0.0",
    "spacy>=3.8.7",
    "uvicorn>=0.34.3",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
